import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Footer } from "@/components/footer/Footer";
import Hotjar from '@hotjar/browser';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const siteId = 5270142;
const hotjarVersion = 6;

Hotjar.init(siteId, hotjarVersion);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     
    <html lang="en">
   
        <script src="//code.tidio.co/rsfmldphxoq1mdgjktlibzuel6zi9nsn.js" async></script>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
            <Footer/>
        </body>

    </html>
  );
}
