import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Footer } from "@/components/footer/Footer";
import HotjarScript from "@/components/HotjarScript";
import Navbar from "@/components/navbar/Navbar";
import NavbarMovil from "@/components/navbarMovil/NavbarMovil";
import NavbarMovilActualizada from "@/components/navbarMovil/NavbarMovilActualizada";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Inicio - EcoAlliance",
  description: "Generated by create next app",
  icons: {
    icon:"/logo.png",
    shortcut:"/logo.png",
    apple:"/logo-apple.png"
  }
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     
    <html lang="en">
       <HotjarScript />
       
        <body
          className={` ${geistSans.variable} ${geistMono.variable} antialiased`}
          >
          
            <Navbar />
            <NavbarMovil/> 
       
            
            {children}
            <Footer/>
        </body>

    </html>
  );
}
