// import SeccionInteres1 from "@/components/seccionInteres/SeccionInteres1"
import Image from "next/image"
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Chipeadoras - EcoAlliance",
    description: "Generated by create next app",
  };



const ProductoGeneral = () =>{
    return(
        <main>
            <section>
                 <Image src="/chipeadora/banner_principal.png" alt="Banner Chipeadoras" width={2000} height={200} />
            </section>

            <section className="mb-20">
                <div className="mt-20">
                    <p className="text-center text-sm">Responde esta pregunta y encuentra la chipeadora ideal para ti.</p>
                    <h2 className="text-center text-2xl mt-2">¿Buscas una chipeadora para podas domésticas o para <br/> procesamiento continuo en grandes proyectos?</h2>   
                </div>
                <div className="md:flex mt-20 px-14 xl:px-52 border shadow-xl pb-10">

                    <div className="w-full md:w-1/2 lg:w-1/3 flex items-center">
                        <div>
                            <div className="flex justify-center">
                                <Image src="/chipeadora/chipeadora_elliet.png" alt="Banner Chipeadoras" width={200} height={200} />
                            </div>
                            <p className="text-center">Chipeadoras portátiles ideales para poda y mantenimiento en el hogar o áreas verdes pequeñas, diseñadas para necesidades básicas de limpieza.</p>
                            <div className="flex justify-center mt-5">
                                <a href={"/chipeadoras/eliet"} className="bg-black text-white py-2 px-7 rounded-full">Ir a Chipeadoras Eliet</a>
                            </div>
                        </div>
                    </div>

                    <div className="hidden lg:block w-1/3 ">
                        <Image src="/chipeadora/hojas.png" alt="Banner Chipeadoras" width={500} height={200} />
                    </div>
                    <div className="w-full md:w-1/2 lg:w-1/3 flex items-center">
                        <div>
                            <div className="flex justify-center">
                                <Image src="/chipeadora/chipeadora_jensen.png" alt="Banner Chipeadoras" width={250} height={250} />

                            </div>
                            <p className="text-center">Chipeadoras ideales para aplicaciones de gran escala como agricultura y paisajismo, diseñadas para manejar grandes volúmenes de poda con eficiencia y resistencia.</p>
                            <div className="flex justify-center mt-5">
                                <a href={"/chipeadoras/jensen"} className="bg-black text-white py-2 px-7 rounded-full">Ir a Chipeadoras Jensen</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* <div className="mb-10 block xl:hidden">
                <h2 className="text-2xl text-center">Productos Relacionados</h2>
            </div>

            <section className="mb-10 md:px-20 flex items-center justify-center">

                    <div className="mr-10 hidden xl:block">
                        <h2 className="text-2xl">Productos <br/>Relacionados</h2>
                    </div>

                    <div className="mx-10 md:flex justify-center  w-full md:w-auto">
                        
                        <div className="w-full  border-gray-200 shadow-xl border-2 rounded-xl p-5 md:w-1/6 lg:w-1/5 md:mx-1 mb-5 md:mb-0">
                            <div className="flex justify-center">
                                <Image src="/chipeadora/cribas.png" alt="Cribas" width={100} height={100} />
                            </div>
                            <h3 className="text-lg text-center mb-3">Cribas</h3>
                            <div className="flex justify-center">
                                <button className="bg-black text-white py-2  px-8 rounded-full text-sm lg:text-md ">Ver producto</button>
                            </div>
                        </div>

                        <div className="w-full border-2 rounded-xl border-gray-200 shadow-xl p-5 md:w-1/6 lg:w-1/5 mx-1 mb-5 md:mb-0">
                            <div className="flex justify-center">
                                <Image src="/chipeadora/briquetadora.png" alt="Briquetadora" width={100} height={100} />
                            </div>
                            <h3 className="text-lg text-center mb-3">Briquetadora</h3>
                            <div className="flex justify-center">
                                <button className="bg-black text-white py-2 px-8 rounded-full text-sm lg:text-md ">Ver producto</button>
                            </div>
                        </div>

                        <div className="w-full border-2 rounded-xl border-gray-200 shadow-xl p-5 md:w-1/6 lg:w-1/5 mx-1 mb-5 md:mb-0">
                        <div className="flex justify-center">
                            <Image src="/chipeadora/trituradora.png" alt="Trituradora" width={100} height={100} />
                        </div>
                            <h3 className="text-lg text-center mb-3">Trituradora</h3>
                            <div className="flex justify-center">
                                <button className="bg-black text-white py-2 px-8 rounded-full text-sm lg:text-md ">Ver producto</button>
                            </div>
                        </div>
                        <div className="w-full border-2 rounded-xl border-gray-200 shadow-xl p-5 md:w-1/6 lg:w-1/5 mx-1 mb-5 md:mb-0">
                            <div className="flex justify-center">
                                <Image src="/chipeadora/volteadora_compost.png" alt="Volteadora compost" width={100} height={100} />
                            </div>
                            <h3 className="text-lg text-center mb-3">Volteadora </h3>
                            <div className="flex justify-center">
                                <button className="bg-black text-white py-2 px-8 rounded-full text-sm lg:text-md ">Ver producto</button>
                            </div>
                        </div>
                        <div className="w-full border-2 rounded-xl border-gray-200 shadow-xl p-5 md:w-1/6 lg:w-1/5 mx-1 mb-5 md:mb-0">
                        <div className="flex justify-center">
                            <Image src="/chipeadora/compostera.png" alt="Compostera" width={100} height={100} />
                        </div>
                            <h3 className="text-lg text-center mb-3">Compostera</h3>
                            <div className="flex justify-center">
                                <button className="bg-black text-white py-2 px-8 rounded-full text-sm lg:text-md ">Ver producto</button>
                            </div>
                        </div>
                    </div>

            </section> */}

            {/* <SeccionInteres1/> */}

        </main>
    )

}

export default ProductoGeneral